{% set name = "alembic" %}
{% set version = "1.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alembic-{{ version }}.tar.gz
  sha256: d8bf706124e96e526889ac9c87a0d50debd9ef325ef32ae5391cf0315bdab4e1

build:
  noarch: python
  entry_points:
    - alembic = alembic.config:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - sqlalchemy >=1.3.0
    - mako
    # Keeping noarch: python for now but may need to constrain these 2 as upstream
    - importlib-metadata
    - importlib_resources
    - typing-extensions >=4

test:
  requires:
    - pip
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util
  commands:
    - pip check
    - alembic --help

about:
  home: https://bitbucket.org/zzzeek/alembic
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A database migration tool for SQLAlchemy.
  dev_url: https://bitbucket.org/zzzeek/alembic
  doc_url: http://alembic.zzzcomputing.com/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - xylar
